site_name: automotive_test_automation
site_url: https://chaitu-ycr.github.io/automotive_test_automation/
site_description: automotive testing and automation notes
site_author: chaitu-ycr

repo_name: chaitu-ycr/automotive_test_automation
repo_url: https://github.com/chaitu-ycr/automotive_test_automation
edit_uri: blob/main/docs/

nav:
  - Home: index.md
  - Notebooks:
    - Testing: Testing/readme.md
    - Tools:
      - CANoe: Tools/CANoe/readme.md
      - CANalyzer: Tools/CANalyzer/readme.md
    - Protocols:
      - CAN: Protocols/CAN/readme.md
      - UDS: Protocols/UDS/readme.md
      - DoIP: Protocols/DoIP/readme.md
    - Automation:
      - CAPL: Automation/CAPL/readme.md
      - Python: Automation/Python/readme.md
      - Jenkins: Automation/Jenkins/readme.md
      - Github_Actions: Automation/Github_Actions/readme.md
    - Test Environments:
      - HiL: Test_Env/HiL/readme.md
      - SiL: Test_Env/SiL/readme.md
      - Bench: Test_Env/Bench/readme.md
    - Build Environments:
      - CMake: Build_Env/CMake/readme.md
    - Projects:
      - ADAS: Projects/ADAS/readme.md
      - BMS: Projects/BMS/readme.md
      - IPC: Projects/IPC/readme.md
      - ABS: Projects/ABS/readme.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
            merge_init_into_class: true
            show_docstring_modules: false
  - include-markdown:
      recursive: true
  - search

theme:
  name: readthedocs
  features:
    - toc.integrate
    - search
