site_name: automotive_test_automation
site_url: https://chaitu-ycr.github.io/automotive_test_automation/
site_description: automotive testing and automation notes
site_author: chaitu-ycr

repo_name: ""
repo_url: https://github.com/chaitu-ycr/automotive_test_automation
edit_uri: blob/main/docs/

nav:
  - Home: index.md
  - Notebooks:
    - Testing:
      - Testing/readme.md
      - ASPICE: Testing/ASPICE/readme.md
    - Tools:
      - CANoe: Tools/CANoe/readme.md
      - CANalyzer: Tools/CANalyzer/readme.md
      - Vector_VN_HW:
        - Tools/Vector_VN_HW/vn_hw_io_piggy.md
    - Protocols:
      - CAN: Protocols/CAN/readme.md
      - UDS: Protocols/UDS/readme.md
      - DoIP: Protocols/DoIP/readme.md
    - Automation:
      - CAPL: Automation/CAPL/readme.md
      - Python:
        - Automation/Python/readme.md
        - Basics:
          - Automation/Python/Basics/000_introduction.ipynb
          - Automation/Python/Basics/001_if_elif_else.ipynb
          - Automation/Python/Basics/002_match_case.ipynb
          - Automation/Python/Basics/003_loops.ipynb
          - Automation/Python/Basics/004_string.ipynb
          - Automation/Python/Basics/005_list.ipynb
          - Automation/Python/Basics/006_tuple.ipynb
          - Automation/Python/Basics/007_set.ipynb
          - Automation/Python/Basics/008_dictionary.ipynb
          - Automation/Python/Basics/009_array.ipynb
          - Automation/Python/Basics/010_functions.ipynb
          - Automation/Python/Basics/011_oop.ipynb
          - Automation/Python/Basics/012_error_exception_handling.ipynb
          - Automation/Python/Basics/013_iterator.ipynb
          - Automation/Python/Basics/014_generator.ipynb
          - Automation/Python/Basics/015_decorator.ipynb
          - Automation/Python/Basics/016_documentation.ipynb
        - Usecases:
          - Automation/Python/Usecases/cantools.ipynb
          - Automation/Python/Usecases/dash.ipynb
          - Automation/Python/Usecases/multiprocessing.ipynb
          - Automation/Python/Usecases/multithreading.ipynb
          - Automation/Python/Usecases/opencv.ipynb
          - Automation/Python/Usecases/pandas.ipynb
          - Automation/Python/Usecases/pillow.ipynb
          - Automation/Python/Usecases/poetry.ipynb
          - Automation/Python/Usecases/pytest.ipynb
          - Automation/Python/Usecases/regular_expressions.ipynb
          - Automation/Python/Usecases/tkinter.ipynb
          - Automation/Python/Usecases/programming_challenges.ipynb
          - Automation/Python/Usecases/z_mixed_examples.ipynb
        - QA:
          - Basics: Automation/Python/QA/python_basics_questions.ipynb
        - Cheatsheets:
          - Basics: Automation/Python/Cheatsheets/python_basics_cheatsheet.pdf
    - Test Environments:
      - HiL: Test_Env/HiL/readme.md
      - SiL: Test_Env/SiL/readme.md
      - Bench: Test_Env/Bench/readme.md
    - Projects:
      - ADAS: Projects/ADAS/readme.md
      - BMS: Projects/BMS/readme.md
      - IPC: Projects/IPC/readme.md
      - ABS: Projects/ABS/readme.md
    - Miscellaneous:
      - YAML:
        - Miscellaneous/YAML/readme.md
        - Miscellaneous/YAML/scalars.ipynb
        - Miscellaneous/YAML/sequences.ipynb
        - Miscellaneous/YAML/mappings.ipynb
        - Miscellaneous/YAML/syntax_and_structure.ipynb
        - Miscellaneous/YAML/miscellaneous.ipynb
      - GIT: Miscellaneous/GIT/readme.md
      - Github_Actions: Miscellaneous/Github_Actions/readme.md
      - Jenkins: Miscellaneous/Jenkins/readme.md
      - CMake: Miscellaneous/CMake/readme.md
      - PlantUML: Miscellaneous/PlantUML/readme.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
            merge_init_into_class: true
            show_docstring_modules: false
  - include-markdown:
      recursive: true
  - mkdocs-jupyter:
      include_requirejs: true
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      puml_keyword: plantuml
      theme:
        light: material/indigo-light
        enabled: false
  - search

theme:
  name: readthedocs
  features:
    - toc.integrate
    - search

extra_css:
  - _assets/extra.css
